version: '3.7'

volumes:
#  mysql56_volume:
#    name: MySql56-Volume
  mysql57_volume:
    name: MySql57-Volume
#  mysql80_volume:
#    name: MySql80-Volume
#  mariadb101_volume:
#    name: MariaDB101-Volume
#  mariadb102_volume:
#    name: MariaDB102-Volume
#  mariadb103_volume:
#    name: MariaDB103-Volume
#  mariadb104_volume:
#    name: MariaDB104-Volume
  mailhog_volume:
    name: MailHog-Volume
#  rabbitmq_volume:
#    name: RabbitMQ-Volume

networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 137.172.0.0/16

services:
#  mysql56:
#    container_name: mysql56
#    image: mysql:5.6
#    restart: always
#    networks:
#      - bridge
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_PASSWORD=root
#    volumes:
#      - mysql56_volume:/var/lib/mysql

  mysql57:
    container_name: mysql57
    image: mysql:5.7
    restart: always
    networks:
      - bridge
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql57_volume:/var/lib/mysql

#  mysql80:
#    container_name: mysql80
#    image: mysql:8.0
#    restart: always
#    networks:
#      - bridge
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_PASSWORD=root
#    volumes:
#      - mysql80_volume:/var/lib/mysql

#  mariadb101:
#    container_name: mariadb101
#    image: bitnami/mariadb:10.1
#    user: root
#    restart: always
#    networks:
#      - bridge
#    environment:
#      - MARIADB_ROOT_USER=root
#      - MARIADB_ROOT_PASSWORD=root
#    volumes:
#      - mariadb101_volume:/bitnami/mariadb

#  mariadb102:
#    container_name: mariadb102
#    image: bitnami/mariadb:10.2
#    user: root
#    restart: always
#    networks:
#      - bridge
#    environment:
#      - MARIADB_ROOT_USER=root
#      - MARIADB_ROOT_PASSWORD=root
#    volumes:
#      - mariadb102_volume:/bitnami/mariadb

#  mariadb103:
#    container_name: mariadb103
#    image: bitnami/mariadb:10.3
#    user: root
#    restart: always
#    networks:
#      - bridge
#    environment:
#      - MARIADB_ROOT_USER=root
#      - MARIADB_ROOT_PASSWORD=root
#    volumes:
#      - mariadb103_volume:/bitnami/mariadb

#  mariadb104:
#    container_name: mariadb104
#    image: bitnami/mariadb:10.4
#    user: root
#    restart: always
#    networks:
#      - bridge
#    environment:
#      - MARIADB_ROOT_USER=root
#      - MARIADB_ROOT_PASSWORD=root
#    volumes:
#      - mariadb104_volume:/bitnami/mariadb

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
#      - mysql56
      - mysql57
#      - mysql80
#      - mariadb101
#      - mariadb102
#      - mariadb103
#      - mariadb104
    links:
#      - mysql56:mysql56
      - mysql57:mysql57
#      - mysql80:mysql80
#      - mariadb101:mariadb101
#      - mariadb102:mariadb102
#      - mariadb103:mariadb103
#      - mariadb104:mariadb104
    networks:
      bridge:
        ipv4_address: 137.172.17.81
    environment:
      - PMA_HOSTS=mysql57,mysql80,mysql56,mariadb101,mariadb102,mariadb103,mariadb104
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ABSOLUTE_URI=http://phpmyadmin.local/
    volumes:
      - /sessions

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    depends_on:
      - phpmyadmin
#      - php7.2-fpm
#      - php7.3-fpm
      - php7.4-fpm
#      - php8.1-fpm
#      - php8.2-fpm
    links:
#      - php7.2-fpm:php7.2-fpm
#      - php7.3-fpm:php7.3-fpm
      - php7.4-fpm:php7.4-fpm
#      - php8.1-fpm:php8.1-fpm
#      - php8.2-fpm:php8.2-fpm
    networks:
      bridge:
        ipv4_address: 137.172.17.80
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - /var/www/hosts:/etc/nginx/conf.d
      - /var/www/html:/var/www/html
      - /var/www/ssl:/var/www/ssl

#  php7.2-fpm:
#    container_name: php7.2-fpm
#    build:
#      context: https://github.com/BlackMaizeGod/php-fpm-docker-service.git
#      dockerfile: Dockerfile
#      args:
#        CONTAINER_VERSION: 72
#    restart: always
#    depends_on:
#      - mailhog
#    links:
#      - mailhog:mailhog
#    networks:
#      - bridge
#    environment:
#      XDEBUG: 'on'
#    volumes:
#      - /var/www/html:/var/www/html

#  php7.3-fpm:
#    container_name: php7.3-fpm
#    build:
#      context: https://github.com/BlackMaizeGod/php-fpm-docker-service.git
#      dockerfile: Dockerfile
#      args:
#        CONTAINER_VERSION: 73
#    restart: always
#    depends_on:
#      - mailhog
#    links:
#      - mailhog:mailhog
#    networks:
#      - bridge
#    environment:
#      XDEBUG: 'on'
#    volumes:
#      - /var/www/html:/var/www/html

  php7.4-fpm:
    container_name: php7.4-fpm
    build:
      context: https://github.com/BlackMaizeGod/php-fpm-docker-service.git
      dockerfile: Dockerfile
      args:
        CONTAINER_VERSION: 74
    restart: always
    depends_on:
      - mailhog
    links:
      - mailhog:mailhog
    networks:
      - bridge
    environment:
      XDEBUG: 'on'
    volumes:
      - /var/www/html:/var/www/html

#  php8.1-fpm:
#    container_name: php8.1-fpm
#    build:
#      context: https://github.com/BlackMaizeGod/php-fpm-docker-service.git
#      dockerfile: Dockerfile
#      args:
#        CONTAINER_VERSION: 81
#    restart: always
#    depends_on:
#      - mailhog
#    links:
#      - mailhog:mailhog
#    networks:
#      - bridge
#    environment:
#      XDEBUG: 'on'
#    volumes:
#      - /var/www/html:/var/www/html

#  php8.2-fpm:
#    container_name: php8.2-fpm
#    build:
#      context: https://github.com/BlackMaizeGod/php-fpm-docker-service.git
#      dockerfile: Dockerfile
#      args:
#        CONTAINER_VERSION: 82
#    restart: always
#    depends_on:
#      - mailhog
#    links:
#      - mailhog:mailhog
#    networks:
#      - bridge
#    environment:
#      XDEBUG: 'on'
#    volumes:
#      - /var/www/html:/var/www/html

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    user: root
    restart: always
    networks:
      bridge:
        ipv4_address: 137.172.17.25
    ports:
      - '1025:1025'
      - '8025:8025'
    volumes:
      - mailhog_volume:/maildir
    command: ['-storage=maildir', '-maildir-path=/maildir']

  elasticsearch7:
    container_name: elasticsearch7
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    restart: always
    networks:
      bridge:
        ipv4_address: 137.172.17.92
    environment:
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - indices.query.bool.max_clause_count=10240
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    ulimits:
      memlock:
        soft: -1
        hard: -1

#  redis:
#    container_name: redis
#    image: redis:latest
#    restart: always
#    networks:
#      - bridge

#  memcached:
#    container_name: memcached
#    image: memcached:1.5
#    restart: always
#    networks:
#      - bridge

#  rabbitmq:
#    container_name: rabbitmq
#    image: rabbitmq:management
#    restart: always
#    hostname: rabbitmq
#    networks:
#      bridge:
#        ipv4_address: 137.172.17.72
#    ports:
#      - '15672:15672'
#      - '5672:5672'
#    environment:
#      - RABBITMQ_DEFAULT_USER=root
#      - RABBITMQ_DEFAULT_PASS=root
#      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
#    volumes:
#      - rabbitmq_volume:/var/lib/rabbitmq